---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-operator
  - https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
  - https://github.com/rabbitmq/messaging-topology-operator/releases/latest/download/messaging-topology-operator-with-certmanager.yaml
